---
server_user: root
ansible_distribution: Ubuntu
ansible_distribution_release: xenial
ansible_python_interpreter: /usr/bin/python3

base_python_package: "{{ ansible_python_interpreter | default('/usr/bin/python') | basename }}"

locale_locales:
  - { locale: en_US.UTF-8, state: present }

locale_language_packs:
  - language-pack-en
  - language-pack-en-base

locale_config_path: /var/lib/locales/supported.d/local

apt_cache_valid_time: 86400